---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - ../../base/operator
  - ../../base/instance
  - grafana-ds.yaml
  - cluster-monitor-view-rb.yaml
  - grafana-auth-secret.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/valuesFrom
        value:
          - targetPath: "secureJsonData.httpHeaderValue1"
            valueFrom:
              secretKeyRef:
                name: grafana-auth-secret
                key: token
    target:
      kind: GrafanaDatasource
      name: prometheus-grafanadatasource

