apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: rhoai-single-model-serving-dashboards
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  resyncPeriod: 5m
  title: RHOAI Single Model Serving Dashboards
